### ISSUE TITLE
Install, No Section: "settings"

### ISSUE THREAD

**Issue by empyrdev** [arcan1s/ffxivbis#2]
![Error](https://i.imgur.com/4I0u9Y9.png)

Getting this whenever I run 
```bash
python -m ffxivbis.application.application
```
both with and without virtualenv.

**Comment by arcan1s** [comment]
it does not check if configuration file exists or not because it is valid case (e.g. configuration settings can be passed by dictionary)

there is configuration example in `package/etc` directory, which (almost) works, thus if you run from `src` directory, you need to

* edit `package/ini/ffxivbis.ini` and specify `web.templates` option as full path to `templates` directory
* in command line set `-c ../package/ini/ffxivbis.ini`, i.e. `python -m ffxivbis.application.application -c ../package/ini/ffxivbis.ini` (if run from src directory)
